// Builds src/geo/land.js: a run-length-encoded land/water mask of the world at
// RES degrees, rasterised from Natural Earth land polygons (public domain, via
// the world-atlas package, ISC). The library ships only the compact mask, so it
// needs no geo dependencies or network access at runtime.
//
//   node scripts/build-land.js [path/to/land-50m.json]
//
// Without a path it downloads world-atlas@2/land-50m.json from jsDelivr.

import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const RES = 0.5; // degrees per mask cell
const COLS = 360 / RES;
const ROWS = 180 / RES;
const SOURCE = 'https://cdn.jsdelivr.net/npm/world-atlas@2/land-50m.json';

const file = process.argv[2];
const topo = JSON.parse(file ? await readFile(file, 'utf8') : await (await fetch(SOURCE)).text());

// ---- TopoJSON decoding (quantized, delta-encoded arcs) -----------------------

const { scale, translate } = topo.transform;
const arcs = topo.arcs.map((arc) => {
  let x = 0;
  let y = 0;
  return arc.map(([dx, dy]) => {
    x += dx;
    y += dy;
    return [x * scale[0] + translate[0], y * scale[1] + translate[1]];
  });
});

const ringOf = (indexes) =>
  indexes.flatMap((i) => (i >= 0 ? arcs[i] : [...arcs[~i]].reverse()));

const rings = [];
const collect = (geom) => {
  if (geom.type === 'GeometryCollection') geom.geometries.forEach(collect);
  else if (geom.type === 'Polygon') geom.arcs.forEach((r) => rings.push(ringOf(r)));
  else if (geom.type === 'MultiPolygon') geom.arcs.forEach((p) => p.forEach((r) => rings.push(ringOf(r))));
};
Object.values(topo.objects).forEach(collect);

// ---- Scanline rasterisation (even-odd), sampling cell centres ------------------

const edges = [];
for (const ring of rings) {
  for (let i = 0; i < ring.length; i++) {
    const a = ring[i];
    const b = ring[(i + 1) % ring.length];
    if (a[1] !== b[1]) edges.push(a, b);
  }
}

const rows = [];
let landCells = 0;
for (let r = 0; r < ROWS; r++) {
  const lat = 90 - (r + 0.5) * RES;
  const xs = [];
  for (let e = 0; e < edges.length; e += 2) {
    const [x0, y0] = edges[e];
    const [x1, y1] = edges[e + 1];
    if (y0 > lat !== y1 > lat) xs.push(x0 + ((lat - y0) * (x1 - x0)) / (y1 - y0));
  }
  xs.sort((a, b) => a - b);
  const row = new Uint8Array(COLS);
  for (let k = 0; k + 1 < xs.length; k += 2) {
    const from = Math.max(0, Math.ceil((xs[k] + 180) / RES - 0.5));
    const to = Math.min(COLS - 1, Math.floor((xs[k + 1] + 180) / RES - 0.5));
    for (let c = from; c <= to; c++) row[c] = 1;
  }
  // Run lengths, alternating water/land, starting with water; base-36.
  const runs = [];
  let value = 0;
  let run = 0;
  for (let c = 0; c < COLS; c++) {
    if (row[c] === value) run++;
    else {
      runs.push(run.toString(36));
      value = row[c];
      run = 1;
    }
    landCells += row[c];
  }
  runs.push(run.toString(36));
  rows.push(runs.join(','));
}

const out = `// Generated by scripts/build-land.js — do not edit by hand.
// Land mask at ${RES}° from Natural Earth (public domain) via world-atlas (ISC).
// Rows run north -> south from 90°N; each row lists run lengths (base 36),
// alternating water/land and starting with water.

export const LAND_RES = ${RES};
export const LAND_COLS = ${COLS};
export const LAND_ROWS = ${ROWS};
export const LAND_RLE = '${rows.join(';')}';
`;
const target = resolve(import.meta.dirname, '../src/geo/land.js');
await writeFile(target, out);
console.log(`wrote ${target}: ${(out.length / 1024).toFixed(1)} KB, ${landCells} land cells (${((landCells / (COLS * ROWS)) * 100).toFixed(1)}%)`);
